name: Deploy
on:
  push:
    branches:
      - production
jobs:
  s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: '${{ runner.os }}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
        env:
          NODE_ENV: development
      - run: npm run generate
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: '--follow-symlinks --delete'
        env:
          AWS_S3_BUCKET: '${{ secrets.AWS_S3_BUCKET }}'
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_REGION: eu-west-1
          SOURCE_DIR: dist
